version: '3.8'

# Docker Compose Override for Official Mailcow-Dockerized
# Connects to existing KumoMTA for cold email delivery

services:
  postfix-mailcow:
    environment:
      - RELAYHOST=kumod-enterprise:25
      - SMTP_SASL_AUTH_ENABLE=no
    networks:
      - kumo-network

networks:
  kumo-network:
    external: true
    name: kumo-network