version: '3.8'

# Docker Compose Override for Official Mailcow-Dockerized
# Connects to KumoMTA via real IP addresses

services:
  postfix-mailcow:
    environment:
      - RELAYHOST=89.117.75.190:2525  # Use internal relay port
      - SMTP_SASL_AUTH_ENABLE=no
    extra_hosts:
      - "kumomta-server:89.117.75.190"
      - "django-server:151.236.251.75"
    # Using real IPs - KumoMTA on standard port 25

  redis-mailcow:
    environment:
      - REDIS_PASSWORD=mailcow_redis_password_2024
    command: redis-server --requirepass mailcow_redis_password_2024 --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru

  dockerapi-mailcow:
    environment:
      - REDIS_PASSWORD=mailcow_redis_password_2024
    depends_on:
      - redis-mailcow