version: '3.2'

services:

  # Mailcow Core Services
  postfix:
    image: mailcow/postfix:latest
    container_name: mailcow-postfix
    restart: unless-stopped
    env_file:
      - mailcow.conf
    environment:
      - RELAYHOST=89.117.75.190:2525
    volumes:
      - ./data/postfix:/var/spool/postfix
      - ./data/mailcow:/opt/mailcow
    networks:
      - mailcow-network
    depends_on:
      - redis
      - mysql

  dovecot:
    image: mailcow/dovecot:latest
    container_name: mailcow-dovecot
    restart: unless-stopped
    env_file:
      - mailcow.conf
    volumes:
      - ./data/dovecot:/var/lib/dovecot
      - ./data/mailcow:/opt/mailcow
    networks:
      - mailcow-network
    depends_on:
      - mysql

  nginx:
    image: mailcow/nginx:latest
    container_name: mailcow-nginx
    restart: unless-stopped
    env_file:
      - mailcow.conf
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/var/lib/nginx
      - ./data/mailcow:/opt/mailcow
      - ./ssl:/ssl
    networks:
      - mailcow-network
    depends_on:
      - postfix
      - dovecot

  mysql:
    image: mailcow/mysql:latest
    container_name: mailcow-mysql
    restart: unless-stopped
    env_file:
      - mailcow.conf
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/mailcow:/opt/mailcow
    networks:
      - mailcow-network

  redis:
    image: mailcow/redis:latest
    container_name: mailcow-redis
    restart: unless-stopped
    env_file:
      - mailcow.conf
    volumes:
      - ./data/redis:/var/lib/redis
    networks:
      - mailcow-network

  # Additional Mailcow Services
  rspamd:
    image: mailcow/rspamd:latest
    container_name: mailcow-rspamd
    restart: unless-stopped
    env_file:
      - mailcow.conf
    volumes:
      - ./data/rspamd:/var/lib/rspamd
      - ./data/mailcow:/opt/mailcow
    networks:
      - mailcow-network

  clamd:
    image: mailcow/clamd:latest
    container_name: mailcow-clamd
    restart: unless-stopped
    env_file:
      - mailcow.conf
    volumes:
      - ./data/clamd:/var/lib/clamav
    networks:
      - mailcow-network

  solr:
    image: mailcow/solr:latest
    container_name: mailcow-solr
    restart: unless-stopped
    env_file:
      - mailcow.conf
    volumes:
      - ./data/solr:/var/lib/solr
    networks:
      - mailcow-network

  sogo:
    image: mailcow/sogo:latest
    container_name: mailcow-sogo
    restart: unless-stopped
    env_file:
      - mailcow.conf
    volumes:
      - ./data/sogo:/var/lib/sogo
      - ./data/mailcow:/opt/mailcow
    networks:
      - mailcow-network
    depends_on:
      - mysql

networks:
  mailcow-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postfix_data:
  dovecot_data:
  mysql_data:
  redis_data:
  nginx_data:
  rspamd_data:
  clamd_data:
  solr_data:
  sogo_data:
