version: '3.8'

# Docker Compose Override for Official Mailcow-Dockerized
# Integrates KumoMTA for cold email delivery

services:
  postfix-mailcow:
    environment:
      - RELAYHOST=kumod-cold-email:2525
      - SMTP_SASL_AUTH_ENABLE=no
    networks:
      - mailcow-network

networks:
  mailcow-network:
    external: true